### PR TITLE
Added cram_tasks.owl for a few more CRAM-specific tasks.

### PR DESCRIPTION
**Pull request by mpomarlan**

### CODE REVIEW

**Review by seba90 — APPROVED** [review]

**Comment by mpomarlan** [comment]
Ok. You can merge this, but best to do so after the other PR is accepted in SOMA (so that the GetTaskParameter concept becomes available in SOMA-ACT.owl)

**Comment by daniel86** [comment]
@mpomarlan could you store in RDF/XML? I would be surprised if KnowRob can handle this format.

**Comment by mpomarlan** [comment]
Done. We can merge this after the other PR from SOMA.

**Comment by mpomarlan** [comment]
I added two task labels "MakeInteriorAccessible" and "MakeInteriorInaccessible". These are intended to correspond to CRAM tasks Accessing and Sealing, respectively. As to why I didn't use the CRAM names, I wanted to use names that somewhat more clearly indicate what the task is about.

**Pull request merged**
